[metadata]
name = bstabdiff
version = 0.2.0
author = Al Zadid Sultan Bin Habib, Md Younus Ahamed, Prashnna Kumar Gyawali, Gianfranco Doretto, Donald A. Adjeroh
description = BSTabDiff: Block-Subunit Diffusion Priors for High-Dimensional Tabular Data Generation (NeurIPS 2026)
long_description = file: README.md
long_description_content_type = text/markdown
license = MIT
license_files = LICENSE
url = https://www.zadidhabib.com/bstabdiff.html

project_urls =
    Homepage = https://www.zadidhabib.com/bstabdiff.html
    Repository = https://github.com/zadid6pretam/BSTabDiff
    Issues = https://github.com/zadid6pretam/BSTabDiff/issues
    Paper = https://openreview.net/forum?id=ciPCMXX1aj

classifiers =
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.10
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent
    Intended Audience :: Science/Research
    Topic :: Scientific/Engineering :: Artificial Intelligence

[options]
packages = find:
python_requires = >=3.10
install_requires =
    numpy==2.2.6
    pandas==2.3.3
    scikit-learn==1.7.2
    scipy==1.15.3
    matplotlib==3.10.8
    tqdm==4.67.3
    torch==2.5.1
    kmeans_gpu==0.0.5
    optuna==4.8.0
    psutil==7.0.0
    codecarbon==3.2.6

include_package_data = True

[options.packages.find]
include =
    bstabdiff
    bstabdiff.*
